commonLabels:
  platform.local/owner: platform-team
deployment:
  podLabels:
    platform.local/owner: platform-team
  replicas: 1
providers:
  kubernetesGateway:
    enabled: true
gateway:
  enabled: false
service:
  type: LoadBalancer
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.localhost`)
    entryPoints: [web]
accessLog:
  enabled: true
resources: {}
