apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    platform.local/owner: platform-team
  name: cluster-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '3'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nyo-platform-engineering/platform-code.git
    targetRevision: main
    path: code/infrastructure/argo-apps/platform/03-policy/policies/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingAdmissionPolicy
      name: vpol-require-workload-owner
      jsonPointers:
        - /spec
        - /metadata/ownerReferences
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
