fullnameOverride: argocd
configs:
  params:
    server.insecure: true
server:
  replicas: 1
  ingress:
    enabled: true
    ingressClassName: traefik
    hostname: argocd.localhost
controller:
  replicas: 1
  metrics:
    enabled: true
repoServer:
  replicas: 1
dex:
  enabled: false
notifications:
  enabled: false
applicationSet:
  replicas: 1
