apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '2'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://grafana-community.github.io/helm-charts
    chart: tempo
    targetRevision: 1.25.0
    helm:
      releaseName: tempo
      valueFiles:
      - $values/code/infrastructure/argo-apps/platform/02-observability/tempo/values.yaml
  - repoURL: https://github.com/nyo-platform-engineering/platform-code.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
