/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAccessGrantsRouteImport } from './routes/admin/access-grants'
import { Route as AdminDataSourcesRouteImport } from './routes/admin/data-sources'
import { Route as AdminOrganizationsRouteImport } from './routes/admin/organizations'
import { Route as LogsIndexRouteImport } from './routes/logs/index'
import { Route as TracesIndexRouteImport } from './routes/traces/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccessGrantsRoute = AdminAccessGrantsRouteImport.update({
  id: '/admin/access-grants',
  path: '/admin/access-grants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDataSourcesRoute = AdminDataSourcesRouteImport.update({
  id: '/admin/data-sources',
  path: '/admin/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/admin/organizations',
  path: '/admin/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIndexRoute = LogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesIndexRoute = TracesIndexRouteImport.update({
  id: '/traces/',
  path: '/traces/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/access-grants': typeof AdminAccessGrantsRoute
  '/admin/data-sources': typeof AdminDataSourcesRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/': typeof AdminIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/traces/': typeof TracesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/access-grants': typeof AdminAccessGrantsRoute
  '/admin/data-sources': typeof AdminDataSourcesRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin': typeof AdminIndexRoute
  '/logs': typeof LogsIndexRoute
  '/traces': typeof TracesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/access-grants': typeof AdminAccessGrantsRoute
  '/admin/data-sources': typeof AdminDataSourcesRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/': typeof AdminIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/traces/': typeof TracesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/access-grants'
    | '/admin/data-sources'
    | '/admin/organizations'
    | '/admin/'
    | '/logs/'
    | '/traces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/access-grants'
    | '/admin/data-sources'
    | '/admin/organizations'
    | '/admin'
    | '/logs'
    | '/traces'
  id:
    | '__root__'
    | '/'
    | '/admin/access-grants'
    | '/admin/data-sources'
    | '/admin/organizations'
    | '/admin/'
    | '/logs/'
    | '/traces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAccessGrantsRoute: typeof AdminAccessGrantsRoute
  AdminDataSourcesRoute: typeof AdminDataSourcesRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  LogsIndexRoute: typeof LogsIndexRoute
  TracesIndexRoute: typeof TracesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/access-grants': {
      id: '/admin/access-grants'
      path: '/admin/access-grants'
      fullPath: '/admin/access-grants'
      preLoaderRoute: typeof AdminAccessGrantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/data-sources': {
      id: '/admin/data-sources'
      path: '/admin/data-sources'
      fullPath: '/admin/data-sources'
      preLoaderRoute: typeof AdminDataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/admin/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/': {
      id: '/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof LogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces/': {
      id: '/traces/'
      path: '/traces'
      fullPath: '/traces/'
      preLoaderRoute: typeof TracesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAccessGrantsRoute: AdminAccessGrantsRoute,
  AdminDataSourcesRoute: AdminDataSourcesRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminIndexRoute: AdminIndexRoute,
  LogsIndexRoute: LogsIndexRoute,
  TracesIndexRoute: TracesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
