apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    platform.local/owner: platform-team
  name: gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '4'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nyo-platform-engineering/platform-code.git
    targetRevision: main
    path: code/infrastructure/argo-apps/platform/04-network/gateway/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
