apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '3'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: 0.173.1
    helm:
      releaseName: otel-collector-cluster
      valueFiles:
      - $values/code/infrastructure/argo-apps/platform/03-observability/otel-collector-cluster/values.yaml
  - repoURL: https://github.com/nyo-platform-engineering/platform-code.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
