apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    platform.local/owner: platform-team
  name: go-demo
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/nyo-platform-engineering/platform-code.git
      targetRevision: main
      path: code/infrastructure/charts/deployment
      helm:
        releaseName: go-demo
        valueFiles:
          - ../../argo-apps/dev/go-demo/values.yaml
          - $app/deploy/values.yaml
    - repoURL: http://gitlab-webservice-default.gitlab.svc.cluster.local:8181/root/go-demo.git
      targetRevision: main
      ref: app
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
