apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '3'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.gitlab.io
      chart: gitlab
      targetRevision: 10.3.2
      helm:
        releaseName: gitlab
        valueFiles:
          - $values/code/infrastructure/argo-apps/platform/03-cd/gitlab/values.yaml
    - repoURL: https://github.com/nyo-platform-engineering/platform-code.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
