apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    platform.local/owner: platform-team
  name: dev-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '5'
spec:
  project: default
  source:
    repoURL: https://github.com/nyo-platform-engineering/platform-code.git
    targetRevision: main
    path: code/infrastructure/argo-apps/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: [ServerSideApply=true]
